language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: DIPhHdCmC6Kxl/SXEvivj8QRvSUBsdM0D1g4+dXA49N1+6WJxZb2+NVY14zHem2xMSHXSHJxBn0GSizlYdjzGuME2JYHcbOY8dsibLs3aW/kOHX99Dp6OAtmkHGmaM5PQg4xc1mPfHrmpRZw9dM/1/OcltNuSgvtK0ONafMewpg=
  - secure: V57YzwrcyCOSvM7UABJKdW4BRLgRA2rv+4+njfkuoveIC0+scYjRbRvmCjPi2CIjlE4Z6K6GuABcGGtqPsIAPv2DlxytrvJbvTLEPx4YLtOFOtPWmnL1gvDzmAo8l1XXcAaq6kBd3z2RJ1woUWqFzRmBI48jP4YGPnO1WniHcLo=
